name = "lin-eclipse-github-oauth"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = true
preview_urls = false

[vars]
ALLOWED_ORIGIN = "https://alexbybye.github.io"
GITHUB_CLIENT_ID = "Ov23lizYsDwIU9vpqlev"

[[kv_namespaces]]
binding = "GITHUB_PUBLIC_CACHE"
id = "5c03986bb4bf459998337992bd301527"

[[durable_objects.bindings]]
name = "SITE_FANS"
class_name = "SiteFans"

[[migrations]]
tag = "site-fans-v1"
new_sqlite_classes = ["SiteFans"]

[triggers]
crons = ["0 0 * * *"]
